export default {
  page: { width: '1922px', height: '2155px' },
  box: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    width: '1922px',
    height: '2155px'
  },
  icon: { position: 'absolute', top: '57px', left: '377px', width: '14px', height: '4px' },
  color: {
    position: 'absolute',
    top: '344px',
    left: '367px',
    backgroundColor: '#339c4f',
    width: '220px',
    height: '5px'
  },
  hd: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '28px',
    marginLeft: '367px',
    width: '387px',
    height: '31px'
  },
  container: {
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '173px',
    height: '31px'
  },
  icon_1: { marginRight: '2px', width: '16px', height: '31px' },
  icon_2: { marginRight: '5px', width: '16px', height: '31px' },
  icon_3: { marginRight: '10px', width: '26px', height: '31px' },
  icon_4: { marginRight: '14px', width: '24px', height: '31px' },
  icon_5: { marginRight: '11px', width: '20px', height: '31px' },
  text: { marginRight: '2px', width: '22px', height: '31px' },
  outer: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '5px',
    height: '5px'
  },
  dot: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '5px', overflow: 'hidden' },
  dot_1: { position: 'relative', width: '5px', height: '5px' },
  actionBg: { width: '161px', height: '31px' },
  bd: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '8px',
    marginLeft: '442px',
    width: '88px',
    height: '8px'
  },
  icon_6: { width: '6px', height: '8px' },
  block: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '1px',
    width: '6px',
    height: '6px'
  },
  icon_7: { position: 'absolute', top: '0px', left: '0px', width: '6px', height: '6px', overflow: 'hidden' },
  icon_8: { position: 'relative', width: '6px', height: '6px' },
  group: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '2px',
    width: '5px',
    height: '6px'
  },
  dot_2: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '6px', overflow: 'hidden' },
  dot_3: { position: 'relative', width: '5px', height: '6px' },
  container_1: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
<<<<<<< HEAD
    marginTop: '2.40vw',
    marginLeft: '2.40vw',
    borderRadius: '2.00vw',
    backgroundColor: 'rgba(0,0,0,0.40)',
    paddingRight: '1.20vw',
    paddingLeft: '1.33vw',
    height: '4.00vw'
  },
  riverdinwei: { opacity: '1.00', width: '1.87vw', height: '2.40vw' },
  distance: {
    marginLeft: '0.53vw',
    height: '2.93vw',
    fontWeight: 400,
    fontSize: '2.40vw',
    color: '#ffffff',
    lineHeight: '2.93vw',
    whiteSpace: 'nowrap'
  },
  main: {
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    width: '45.60vw',
    height: '15.20vw'
  },
  title: {
    marginTop: '2.93vw',
    width: '40.00vw',
    height: '11.73vw',
    fontWeight: 400,
    fontSize: '4.00vw',
    color: '#333333',
    lineHeight: '5.87vw',
    overflow: 'hidden',
    textOverflow: 'ellipsis'
  },
  ft: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomLeftRadius: '1.60vw',
    borderBottomRightRadius: '1.60vw',
    backgroundColor: '#ffffff',
    paddingRight: '2.27vw',
    paddingLeft: '2.40vw',
    width: '45.60vw',
    height: '10.40vw',
    overflow: 'hidden'
  },
  block: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '4.00vw' },
  xianjin: { width: '4.00vw', height: '4.00vw' },
  fashionHome: {
    marginLeft: '0.80vw',
    height: '3.73vw',
    fontWeight: 300,
    fontSize: '3.20vw',
    color: '#666666',
    lineHeight: '3.73vw',
    whiteSpace: 'nowrap'
  },
  group: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '4.00vw' },
  favorite: { width: '2.93vw', height: '2.93vw' },
  num: {
    marginLeft: '0.67vw',
    height: '3.47vw',
    fontWeight: 400,
    fontSize: '2.93vw',
    color: '#999999',
    lineHeight: '3.47vw',
    whiteSpace: 'nowrap'
=======
    justifyContent: 'center',
    marginRight: '2px',
    width: '5px',
    height: '6px'
  },
  dot_4: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '6px', overflow: 'hidden' },
  dot_5: { position: 'relative', width: '5px', height: '6px' },
  play: { marginRight: '5px', width: '5px', height: '8px' },
  dot_6: { marginRight: '2px', width: '5px', height: '8px' },
  block_1: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '1px',
    width: '5px',
    height: '6px'
  },
  dot_7: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '6px', overflow: 'hidden' },
  dot_8: { position: 'relative', width: '5px', height: '6px' },
  dot_9: { marginRight: '1px', width: '5px', height: '6px' },
  group_1: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '3px',
    width: '5px',
    height: '8px'
  },
  dot_10: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '8px', overflow: 'hidden' },
  dot_11: { position: 'relative', width: '5px', height: '8px' },
  play_1: { marginRight: '1px', width: '5px', height: '8px' },
  container_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '1px',
    width: '6px',
    height: '6px'
  },
  icon_9: { position: 'absolute', top: '0px', left: '0px', width: '6px', height: '6px', overflow: 'hidden' },
  icon_10: { position: 'relative', width: '6px', height: '6px' },
  dot_12: { marginRight: '2px', width: '5px', height: '6px' },
  dot_13: { marginTop: '-6px', width: '4px', height: '2px' },
  submain: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-end',
    flexDirection: 'row',
    marginTop: '15px',
    marginLeft: '1px',
    backgroundColor: '#d8d8d8',
    width: '1920px',
    height: '186px'
  },
  layer: { position: 'absolute', top: '0px', left: '0px', width: '1920px', height: '186px' },
  summary: {
    position: 'absolute',
    top: '110px',
    left: '366px',
    lineHeight: '33px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '24px',
    fontWeight: 400
  },
  title: {
    position: 'relative',
    marginRight: '145px',
    marginBottom: '57px',
    marginLeft: '366px',
    lineHeight: '96px',
    whiteSpace: 'nowrap',
    color: '#339c4f',
    fontSize: '48px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  info: {
    position: 'relative',
    marginBottom: '45px',
    maxWidth: '1025px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  info_1: {
    position: 'relative',
    marginTop: '34px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#1a1a1a',
    fontSize: '16px',
    fontWeight: 500
  },
  row: {
    position: 'relative',
    marginTop: '18px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(230,230,230,1)',
    width: '1922px',
    height: '2px'
  },
  article: {
    position: 'relative',
    marginTop: '28px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  summary_1: {
    position: 'relative',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  txt: {
    position: 'relative',
    marginTop: '10px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  article_1: {
    position: 'relative',
    marginTop: '10px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  summary_2: {
    position: 'relative',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  row1: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '21px',
    marginLeft: '1392px',
    backgroundColor: '#339c4f',
    paddingRight: '39px',
    paddingLeft: '39px',
    height: '36px'
  },
  txt_1: { lineHeight: '20px', whiteSpace: 'nowrap', color: '#ffffff', fontSize: '16px', fontWeight: 500 },
  row2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'column',
    marginTop: '27px',
    backgroundColor: 'rgba(216,216,216,0.09)',
    width: '1190px',
    height: '545px'
  },
  colorDiv: {
    position: 'relative',
    marginTop: '19px',
    marginLeft: '22px',
    backgroundColor: '#339c4f',
    width: '260px',
    height: '5px'
  },
  div: {
    position: 'relative',
    marginTop: '30px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(151,151,151,1)',
    width: '1190px',
    height: '2px'
  },
  descWrap: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'absolute',
    top: '24px',
    left: '302px',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#d8d8d8',
    paddingRight: '15px',
    paddingLeft: '16px',
    height: '60px'
  },
  desc: { lineHeight: '22px', whiteSpace: 'pre', color: '#1a1a1a', fontSize: '16px', fontWeight: 500 },
  group_2: {
    display: 'flex',
    position: 'absolute',
    top: '24px',
    left: '22px',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fbfbfb',
    width: '260px',
    height: '60px'
  },
  color_1: { backgroundColor: '#339c4f', width: '1px', height: '60px' },
  desc_1: {
    maxWidth: '213px',
    height: '22px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '16px',
    fontWeight: 500
  },
  color_2: { backgroundColor: '#339c4f', width: '1px', height: '60px' },
  container_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '75px',
    width: '1146px',
    height: '320px'
  },
  block_2: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '320px' },
  summary_3: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_4: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_5: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  info_2: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_6: {
    position: 'relative',
    marginTop: '10px',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  info_3: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  txt_2: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  info_4: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  text_1: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  txt_3: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  desc_2: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_7: {
    position: 'relative',
    marginTop: '10px',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_8: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  desc_3: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_9: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  banner: { width: '621px', height: '311px' },
  block_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '10px',
    width: '1146px',
    height: '40px'
  },
  group_3: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '40px' },
  summary_10: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  desc_4: {
    position: 'relative',
    maxWidth: '479px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  infoWrap: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '4px',
    backgroundColor: '#339c4f',
    paddingRight: '23px',
    paddingLeft: '23px',
    height: '36px'
  },
  info_5: { lineHeight: '20px', whiteSpace: 'nowrap', color: '#ffffff', fontSize: '16px', fontWeight: 500 },
  txt_4: {
    position: 'relative',
    marginTop: '40px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '16px',
    fontWeight: 500
  },
  main: {
    position: 'relative',
    marginTop: '13px',
    marginLeft: '367px',
    backgroundColor: '#339c4f',
    width: '106px',
    height: '5px'
  },
  row3: {
    position: 'relative',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(230,230,230,1)',
    width: '1922px',
    height: '2px'
  },
  word: {
    position: 'relative',
    marginTop: '29px',
    marginLeft: '389px',
    maxWidth: '1533px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '14px',
    fontWeight: 500
  },
  row4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '60px',
    marginLeft: '476px',
    backgroundColor: '#f0f0f0',
    width: '430px',
    height: '14px'
  },
  icon_11: { position: 'absolute', top: '0px', left: '66px', width: '14px', height: '14px' },
  icon_12: { position: 'relative', marginRight: '239px', width: '14px', height: '14px' },
  icon_13: { position: 'relative', width: '14px', height: '14px' },
  icon_14: { position: 'absolute', top: '0px', right: '77px', width: '14px', height: '14px' },
  group_4: {
    display: 'flex',
    position: 'absolute',
    top: '1279px',
    left: '904px',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '88px',
    height: '88px'
  },
  pic: { position: 'absolute', top: '0px', left: '0px', width: '88px', height: '88px' },
  group_5: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '-4px',
    width: '42px',
    height: '40px'
  },
  icon_15: { position: 'absolute', top: '0px', left: '0px', width: '42px', height: '40px', overflow: 'hidden' },
  outer_1: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '42px',
    height: '40px'
  },
  icon_16: { position: 'absolute', top: '0px', left: '0px', width: '42px', height: '40px' },
  locate: { position: 'relative', marginTop: '13px', width: '4px', height: '23px' },
  group_6: {
    display: 'flex',
    position: 'absolute',
    top: '1279px',
    left: '637px',
    alignItems: 'center',
    flexDirection: 'row',
    width: '88px',
    height: '88px'
  },
  pic_1: { position: 'absolute', top: '0px', left: '0px', width: '88px', height: '88px' },
  group_7: {
    display: 'flex',
    position: 'absolute',
    top: '20px',
    right: '22px',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '41px',
    height: '45px'
  },
  icon_17: { position: 'absolute', top: '0px', left: '0px', width: '41px', height: '45px', overflow: 'hidden' },
  outer_2: { position: 'relative', width: '41px', height: '45px' },
  block_4: {
    display: 'flex',
    position: 'absolute',
    top: '28px',
    right: '16px',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '40px',
    height: '35px'
  },
  icon_18: { position: 'absolute', top: '0px', left: '0px', width: '40px', height: '35px', overflow: 'hidden' },
  icon_19: { position: 'relative', width: '40px', height: '35px' },
  group_8: {
    display: 'flex',
    position: 'absolute',
    top: '1279px',
    left: '389px',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '88px',
    height: '88px'
  },
  pic_2: { position: 'absolute', top: '0px', left: '0px', width: '88px', height: '88px' },
  group_9: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '43px',
    height: '36px'
  },
  icon_20: { position: 'absolute', top: '0px', left: '0px', width: '43px', height: '36px', overflow: 'hidden' },
  outer_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    width: '43px',
    height: '36px'
  },
  icon_21: { position: 'absolute', top: '0px', left: '0px', width: '43px', height: '36px' },
  locate_1: { position: 'absolute', top: '11px', left: '11px', width: '10px', height: '10px' },
  icon_22: { position: 'relative', marginTop: '-7px', marginLeft: '16px', width: '16px', height: '13px' },
  row5: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '52px',
    marginLeft: '405px',
    height: '40px'
  },
  col: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginRight: '192px',
    width: '56px',
    height: '40px'
  },
  step: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#339c4f',
    fontSize: '14px',
    fontWeight: 500,
    alignSelf: 'baseline'
  },
  stepNext: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  col_1: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginRight: '211px',
    width: '56px',
    height: '40px'
  },
  step_1: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#339c4f',
    fontSize: '14px',
    fontWeight: 500,
    alignSelf: 'baseline'
  },
  stepNext_1: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  col_2: { display: 'flex', alignItems: 'center', flexDirection: 'column', width: '56px', height: '40px' },
  step_2: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#339c4f',
    fontSize: '14px',
    fontWeight: 500,
    alignSelf: 'baseline'
  },
  stepNext_2: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  text_2: {
    position: 'relative',
    marginTop: '31px',
    marginLeft: '389px',
    maxWidth: '1533px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '14px',
    fontWeight: 500
  },
  article_2: {
    position: 'relative',
    marginTop: '10px',
    marginLeft: '389px',
    maxWidth: '1533px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  summary_11: {
    position: 'relative',
    marginLeft: '389px',
    maxWidth: '1533px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400
  },
  row6: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: '389px',
    height: '20px'
  },
  count: {
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  desc_5: {
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#339c4f',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  summary_12: {
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '14px',
    fontWeight: 400,
    alignSelf: 'baseline'
  },
  num: {
    position: 'absolute',
    top: '1514px',
    right: '929px',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 500
  },
  txt_5: {
    position: 'relative',
    marginTop: '31px',
    marginLeft: '389px',
    maxWidth: '1533px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '14px',
    fontWeight: 500
  },
  row7: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '23px',
    marginLeft: '389px',
    width: '917px',
    height: '201px'
  },
  container_4: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '201px' },
  group_10: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(225,225,225,1)',
    backgroundColor: '#ffffff',
    width: '200px',
    height: '153px'
  },
  wrap: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '128px',
    height: '140px'
  },
  smallPic: { position: 'absolute', top: '0px', left: '0px', width: '128px', height: '140px', overflow: 'hidden' },
  smallImg: { position: 'relative', width: '128px', height: '140px' },
  infoWrap_1: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#339c4f',
    width: '200px',
    height: '48px'
  },
  info_6: {
    maxWidth: '188px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 500
  },
  container_5: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '201px' },
  group_11: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(225,225,225,1)',
    backgroundColor: '#ffffff',
    width: '200px',
    height: '153px'
  },
  wrap_1: { width: '153px', height: '137px' },
  infoWrap_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#339c4f',
    width: '200px',
    height: '48px'
  },
  info_7: {
    maxWidth: '188px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 500
  },
  container_6: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '201px' },
  group_12: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(225,225,225,1)',
    backgroundColor: '#ffffff',
    width: '200px',
    height: '153px'
  },
  wrap_2: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '4px',
    width: '154px',
    height: '134px'
  },
  smallPic_1: { position: 'absolute', top: '0px', left: '0px', width: '154px', height: '134px', overflow: 'hidden' },
  smallImg_1: { position: 'relative', width: '154px', height: '134px' },
  infoWrap_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#339c4f',
    width: '200px',
    height: '48px'
  },
  info_8: {
    maxWidth: '188px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 500
  },
  container_7: { display: 'flex', alignItems: 'flex-start', flexDirection: 'column', height: '201px' },
  group_13: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(225,225,225,1)',
    backgroundColor: '#ffffff',
    width: '200px',
    height: '153px'
  },
  wrap_3: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '-8px',
    borderRadius: '8px',
    backgroundColor: '#d13b3b',
    width: '140px',
    height: '72px'
  },
  smallPic_2: { position: 'relative', marginRight: '7px', marginBottom: '9px', width: '57px', height: '50px' },
  smallImg_2: {
    position: 'relative',
    marginRight: '2px',
    marginBottom: '28px',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 600,
    alignSelf: 'baseline'
  },
  price: {
    position: 'relative',
    marginBottom: '21px',
    lineHeight: '50px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '36px',
    fontWeight: 600,
    alignSelf: 'baseline'
  },
  txt_6: {
    position: 'absolute',
    right: '15px',
    bottom: '6px',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 600
  },
  colorDiv_1: {
    position: 'absolute',
    top: '85px',
    left: '22px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  colorDiv_2: {
    position: 'absolute',
    top: '85px',
    right: '20px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  colorDiv_3: {
    position: 'absolute',
    top: '66px',
    left: '22px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  colorDiv_4: {
    position: 'absolute',
    top: '66px',
    right: '20px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  colorDiv_5: {
    position: 'absolute',
    top: '48px',
    left: '22px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  colorDiv_6: {
    position: 'absolute',
    top: '48px',
    right: '20px',
    borderRadius: '6.5px',
    backgroundColor: '#ffffff',
    width: '13px',
    height: '13px'
  },
  infoWrap_4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#339c4f',
    width: '200px',
    height: '48px'
  },
  info_9: {
    maxWidth: '188px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'pre',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: 500
  },
  info_10: {
    position: 'relative',
    marginTop: '31px',
    marginLeft: '388px',
    maxWidth: '1534px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#1a1a1a',
    fontSize: '14px',
    fontWeight: 500
  },
  ft: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'column',
    marginTop: '49px',
    marginLeft: '1px',
    backgroundColor: '#141414',
    width: '1920px',
    height: '237px'
  },
  icon_23: { position: 'absolute', top: '79px', left: '400px', width: '13px', height: '4px' },
  block_5: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '53px',
    marginLeft: '391px',
    width: '157px',
    height: '29px'
  },
  icon_24: { marginRight: '3px', width: '14px', height: '29px' },
  icon_25: { marginRight: '4px', width: '14px', height: '29px' },
  icon_26: { marginRight: '10px', width: '24px', height: '29px' },
  icon_27: { marginRight: '12px', width: '22px', height: '29px' },
  icon_28: { marginRight: '10px', width: '18px', height: '29px' },
  text_3: { marginRight: '2px', width: '20px', height: '29px' },
  group_14: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '4px',
    height: '4px'
  },
  dot_14: { position: 'absolute', top: '0px', left: '0px', width: '4px', height: '4px', overflow: 'hidden' },
  dot_15: { position: 'relative', width: '4px', height: '4px' },
  group_15: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '6px',
    marginLeft: '460px',
    width: '80px',
    height: '8px'
  },
  dot_16: { marginRight: '1px', width: '5px', height: '7px' },
  container_8: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '1px',
    width: '5px',
    height: '5px'
  },
  dot_17: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '5px', overflow: 'hidden' },
  dot_18: { position: 'relative', width: '5px', height: '5px' },
  outer_4: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '2px',
    width: '4px',
    height: '5px'
  },
  dot_19: { position: 'absolute', top: '0px', left: '0px', width: '4px', height: '5px', overflow: 'hidden' },
  dot_20: { position: 'relative', width: '4px', height: '5px' },
  block_6: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '1px',
    width: '5px',
    height: '5px'
  },
  dot_21: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '5px', overflow: 'hidden' },
  dot_22: { position: 'relative', width: '5px', height: '5px' },
  play_2: { marginRight: '6px', width: '4px', height: '7px' },
  dot_23: { width: '5px', height: '7px' },
  group_16: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '3px',
    width: '4px',
    height: '5px'
  },
  dot_24: { position: 'absolute', top: '0px', left: '0px', width: '4px', height: '5px', overflow: 'hidden' },
  play_3: { position: 'relative', width: '4px', height: '5px' },
  dot_25: { width: '5px', height: '5px' },
  container_9: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '2px',
    width: '5px',
    height: '8px'
  },
  dot_26: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '8px', overflow: 'hidden' },
  dot_27: { position: 'relative', width: '5px', height: '8px' },
  play_4: { marginRight: '1px', width: '4px', height: '7px' },
  outer_5: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: '2px',
    width: '5px',
    height: '5px'
  },
  dot_28: { position: 'absolute', top: '0px', left: '0px', width: '5px', height: '5px', overflow: 'hidden' },
  dot_29: { position: 'relative', width: '5px', height: '5px' },
  dot_30: { marginRight: '1px', width: '5px', height: '5px' },
  dot_31: { marginTop: '-4px', width: '4px', height: '2px' },
  article_3: {
    position: 'relative',
    marginTop: '21px',
    marginLeft: '391px',
    maxWidth: '1529px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 500,
    alignSelf: 'baseline'
  },
  summary_13: {
    position: 'relative',
    marginLeft: '391px',
    maxWidth: '1529px',
    height: '20px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 500,
    alignSelf: 'baseline'
  },
  container_10: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: '391px',
    width: '411px',
    height: '20px'
  },
  httpwwwavnetcomapac: {
    position: 'absolute',
    top: '0px',
    right: '14px',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#339c4f',
    fontSize: '14px',
    fontWeight: 500
  },
  nickName: {
    position: 'relative',
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 500
>>>>>>> fec891e... init
  }
};
